config/routes.rb
Rails.application.routes.draw do
  root 'skys#ask'

  get 'get', to: 'skys#get'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/skys_controller.rb
require 'net/http'
class SkysController < ApplicationController
  def ask
  end

  def get
    @start_time = params[:event_starttime]
    @end_time = params[:event_endtime]
    nasa_ask = "http://www.lmsal.com/hek/her?cosec=2&cmd=search&type=column&event_type=fl,fe,er,fi,cw,lp,ss,cj,sp,pt,ar,cr,bu,ee&event_starttime=#{@start_time}T00:00:00&event_endtime=#{@end_time}T00:00:00&temporalmode=strict&event_coordsys=helioprojective&x1=-1200&x2=1200&y1=-1200&y2=1200"
    @nasa_info = Net::HTTP.get(URI(nasa_ask))
    @nasa_easy = JSON.parse @nasa_info
    @nasa_result = @nasa_easy['result']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skys_helper.rb
module SkysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Api</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skys/ask.html.erb
<section class='container '>
	<h1> Search Date for Solar Activity </h1>
	<p> Boiler Plate for Science API Call </p>
  <center>
	<%= form_tag get_path, method: "get", html: { class: "form" } do %>
 	<div class="form-group col-sm-6 col-md-offset-3">
   <%= text_field_tag(:event_starttime, "", placeholder: " Start Date:  YYYY-MM-DD ", class: "form-control") %>
 	</div>
 	<div class="form-group col-sm-6 col-md-offset-3">
   	<%= text_field_tag(:event_endtime, "", placeholder: " End Date:  YYYY-MM-DD", class: "form-control") %>
 	</div>
</center>
 	<center><div class="form-group col-sm-12">
 	<%=submit_tag "Search", class: "btn btn-info", style:'width: 50%'%>
	<% end %>
</section>

app/views/skys/get.html.erb
<section class='container col-sm-12'>
  <h1 class='space1'> Solar Data from Gets14 </h1>


 <h1><center><%=@start_time%> - <%=@end_time%></center></h1>

<section class= 'container col-sm-12'>
  <% @nasa_result.each do |info| %>
     <% if info['gs_imageurl'] != "" %>
        <center><img src="<%= info["gs_imageurl"] %>" /></center>
      <%end%>
  <%end%>
</section>
</section>
<section class='container col-sm-12'>
  <% @nasa_result.each do |info| %>
    <% if info['gs_movieurl'] != "" %>
      <center><video src ="<%= info['gs_movieurl']%>"controls width="720" height="640"/></center>
      <%= info["event_type"] %>

    <%end%>
  <%end%>
</section>